/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Submission = IDL.Record({
  'originalText' : IDL.Text,
  'timestamp' : Time,
  'variations' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addSubmission' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'clearHistory' : IDL.Func([], [], []),
  'getAllUsersWithHistory' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getSubmissionByTimestamp' : IDL.Func([IDL.Int], [Submission], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'originalText' : IDL.Text,
    'timestamp' : Time,
    'variations' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addSubmission' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'clearHistory' : IDL.Func([], [], []),
    'getAllUsersWithHistory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getHistory' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getSubmissionByTimestamp' : IDL.Func([IDL.Int], [Submission], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };